[tox]
envlist = python313
package = wheel
wheel_build_env = .pkg

[testenv:python313]
deps =
    pytest==9.0.2
    -r requirements.txt
    -r requirements.test.txt
commands = pytest tests/ -n 5 --forked
base_python = python3.13